### ISSUE TITLE
 else if issue 

### ISSUE THREAD

**Issue by Duck8267** [berkay-yalin/berkay-yalin.io#1]
### BROKEN VERSION
```
if a == 3 then
    print(3)
else if b == 3 then
    print(2+2)
endif
```
_causes bug_ 
```
if a == 3:
    print(3)
else if b == 3 then
    print(2+2)

```
### WORKING VERSION:
```
if a == 3 then
    print(3)
elseif b == 3 then
    print(2+2)
endif
```
_no bug 
causes:_
```
if a == 3:
    print(3)
elif b == 3:
    print(2+2)
```

**Comment by ostromia** [comment]
thanks for the report @Duck8267, issue should be fixed now:

https://github.com/berkay-yalin/berkay-yalin.io/blob/79ad1c2074f139b306927fb812047f008cc4f56e/src/routes/zygon/transpiler/transpiler.ts#L328-L356
